config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :edit, :update]
  resources :posts, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :follows, only: [:create, :destroy]

  get '/profile/:id', to: "users#show", as: "user"
  get '/profile/:id/followings', to: "users#followings", as: "following"
  get '/profile/:id/followers', to: "users#followers", as: "followers"
  post '/users/search', to: "users#search", as: :search
  get '/users/search', to: "users#search"
  
  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
   def initialize(user)
     if user
       can :read, :all
       can :manage, Post, user_id: user.id
       can :manage, Follow, user_id: user.id
       can :manage, Like, user_id: user.id
       can :manage, Comment, user_id: user.id
     end
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes

  acts_as_commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  
  has_many :posts
  has_many :likes

  acts_as_followable
  acts_as_follower
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  load_and_authorize_resource
  
  def create
  end

  def destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  load_and_authorize_resource
  
  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def show
  end

  def followers
  end

  def followings
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedeSocial</title>
    <%= csrf_meta_tags %>
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <header>
      <%= render "shared/navbar" %>
    </header>
    <main>      
      <div class="container">
        <%= yield %>
      </div>
    </main>
 
    <footer>
      <%= render "shared/footer" %>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'red')" %>
      <% else message_type == 'notice' %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000, 'green')" %>
      <% end%>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row home">
  <div class="center">
    <h4 class="title">A Programmer Networking</h4>
    <h5 class="subtitle">Join to ProgrammerHub and connect with thousands of other software developers to learn and share</h5>
 
    <%= link_to 'Join Now', new_user_registration_path, class: "btn btn-large grey darken-2 home-button"  %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="copyright">
      <b>
        <a class="copyright-link" href="http://onebitcode.com/">Created with<i class="material-icons copyright-icon">favorite</i> By OneBitCode</a>
      </b>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <div class="container">
        <% if current_user %>
          <a href="/posts" class="brand-logo">
            <i class="material-icons">group</i>
            <span class="logo-title">
              ProgrammerHub
            </span>
          </a>
        <% else %>
          <a href="/" class="brand-logo">
            <i class="material-icons">group</i>
            <span class="logo-title">
              ProgrammerHub
            </span>
          </a>
        <% end %>

        <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>

        <ul class="right hide-on-med-and-down">
          <% if current_user %>
            <li>
              <a class="dropdown-button" href="#!" data-activates="dropdown1">
                <img src="<%= current_user.avatar.thumb.url %>" alt="" class="responsive-img circle nav-image">
              </a>
            </li>

            <ul id="dropdown1" class="dropdown-content">
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          <% else %>
            <li><a href="/users/sign_in">Login</a></li>
            <li><a href="/users/sign_up">Register</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li><%= link_to 'Feed', posts_path %></li>
    <li><%= link_to 'Profile', user_path(current_user) %></li>
    <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Log in</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Register</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>